### ISSUE TITLE
Button text slightly cut on the bottom

### ISSUE THREAD

**Issue by alexmurari** [PluralCrypt/PluralCrypt#7]
**Current Behavior**
The current layout of the main form deforms the buttons.

**Expected Behavior**
The buttons shoudn't be deformed and there should enough form space to accomodate them.

**Steps to Reproduce**
1. Open main form.
2 See the broken layout.

**Additional context**
Version 2.1.0

![image](https://user-images.githubusercontent.com/11204378/90078981-f9cb7d80-dcdc-11ea-82c6-26cff6f379ea.png)

**Comment by sitiom** [comment]
I don't see any problem except the text in the buttons being cut on the bottom. It seems to be a scaling problem.

**Comment by alexmurari** [comment]
That's what I meant. It's not a show-stopper, but it's something that be taken care of.

**Comment by sitiom** [comment]
Fixed now.
